package com.healthcare.clinic.clinicaldecision.service;

import com.healthcare.clinic.patient.entity.PatientProfile;
import com.healthcare.clinic.patient.repository.PatientProfileRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
@Slf4j
@RequiredArgsConstructor
public class CdsAiInsightService {

    private final PatientProfileRepository patientProfileRepository;

    /**
     * Simulates an AI model generating clinical insights based on patient history and a list of proposed medications.
     */
    public String generateClinicalInsight(Long patientId, List<String> medications) {
        if (medications == null || medications.isEmpty()) {
            return "No medications provided for analysis.";
        }

        Optional<PatientProfile> patientOpt = patientProfileRepository.findByUserId(patientId);
        String patientAllergiesStr = patientOpt.map(p -> p.getAllergies() != null ? p.getAllergies().toUpperCase() : "NONE").orElse("NONE");
        String patientConditionsStr = patientOpt.map(p -> p.getChronicConditions() != null ? p.getChronicConditions().toUpperCase() : "NONE").orElse("NONE");

        String medsStr = medications.stream().map(String::toUpperCase).collect(Collectors.joining(", "));

        // Simulated AI logic
        StringBuilder insight = new StringBuilder();
        insight.append("### AI Clinical Insight Report\n\n");
        insight.append("**Patient Profile Summary:**\n");
        insight.append("- Known Allergies: ").append(patientAllergiesStr).append("\n");
        insight.append("- Chronic Conditions: ").append(patientConditionsStr).append("\n\n");
        insight.append("**Proposed Medications:** ").append(medsStr).append("\n\n");

        boolean hasWarning = false;

        if (patientConditionsStr.contains("DIABETES") || patientConditionsStr.contains("CKD")) {
            if (medsStr.contains("IBUPROFEN") || medsStr.contains("NAPROXEN")) {
                insight.append("⚠️ **Interaction Warning:** Use caution prescribing NSAIDs (like ").append(medsStr).append(") to patients with renal or metabolic conditions. ");
                insight.append("Consider a lower dosage or alternative pain management strategy.\n\n");
                hasWarning = true;
            }
        }

        if (medsStr.contains("AMOXICILLIN") && medsStr.contains("METRONIDAZOLE")) {
            insight.append("💡 **Guideline Note:** The combination of Amoxicillin and Metronidazole is effective for mixed aerobic-anaerobic infections (e.g., dental or intra-abdominal). ");
            insight.append("Ensure the patient is advised to avoid alcohol completely during the Metronidazole course.\n\n");
            hasWarning = true;
        }

        if (medsStr.contains("METFORMIN")) {
            insight.append("💡 **Dosing Recommendation:** For Metformin, start with 500mg once daily with meals to minimize gastrointestinal side effects, titrating up slowly as tolerated.\n\n");
            hasWarning = true;
        }

        if (!hasWarning) {
            insight.append("✅ **Safety Check Passed:** No significant AI-detected interactions or contraindications found based on the provided patient history and standard guidelines.\n\n");
        }

        insight.append("*Disclaimer: This insight is generated by an AI assistant for demonstrative purposes and should not replace clinical judgment.*");

        return insight.toString();
    }
}
